### ISSUE TITLE
Adding multiple coverage reports to a single workflow

### ISSUE THREAD

**Issue by aprehatny** [davelosert/vitest-coverage-report-action#231]
I am currently trying to add coverage reports with separate coverage gates between .ts and .tsx files, based on my configuration in my workflow yaml file, the coverage reporter post is being overwritten depending on the coverage reporter step i have defined later in the steps.
Here is my configuration:

```yaml
      - name: Generate .tsx coverage report
        run: |
          npm run coverage:tsx
        if: always() # Also generate the report if tests are failing

      - name: Report .tsx File Coverage
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          json-summary-path: './coverage/tsx/coverage-summary.json'
          json-final-path: './coverage/tsx/coverage-final.json'

      - name: Generate .ts coverage report
        run: |
          npm run coverage:ts
        if: always() # Also generate the report if tests are failing

      - name: Report .ts File Coverage
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          json-summary-path: './coverage/ts/coverage-summary.json'
          json-final-path: './coverage/ts/coverage-final.json'
```
I am looking for a way to ensure that the two separate coverages can post on the same PR, hoping this is something that is supported or there is a workaround, thanks!
