### ISSUE TITLE
Unable to find config file ".//".

### ISSUE THREAD

**Issue by productdevbook** [davelosert/vitest-coverage-report-action#259]
Error ci
```sh
Run davelosert/vitest-coverage-report-action@v2
  with:
    working-directory: ./
    github-token: ***
    json-summary-path: coverage/coverage-summary.json
    file-coverage-mode: changes
    json-final-path: coverage/coverage-final.json
Error: Failed to read vite config file".//" or any of the default locations.
Make sure you provide the vite-config-path option if you're using a non-default location or name of your config file.
Error: Error: Unable to find config file ".//".

```

My config
```yml
name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:

    name: 📚 Main
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧪 Server Test
        run: pnpm test:server
        env:
          VITE_TEST_DB_URL: postgres://postgres:postgres@127.0.0.1:5432

      - name: 🧪 Server Test Coverage
        run: pnpm test:server:cov
        env:
          VITE_TEST_DB_URL: postgres://postgres:postgres@127.0.0.1:5432

      - name: 📝 Upload coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: './'

```
