### ISSUE TITLE
Failed to parse the json-summary when specifying custom path and tests are failing

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [davelosert/vitest-coverage-report-action#307]
I put the `coverage` under the top `output` directory.

Workflow:
```yaml
      - name: Run test
        run: pnpm test:coverage

      - name: Report Coverage
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: ./output/coverage/coverage-summary.json
          json-final-path: ./output/coverage/coverage-final.json
```

**vite.config.ts**
```ts
import { defineConfig } from 'vite'
import GithubActionsReporter from 'vitest-github-actions-reporter'

const isInCI = !!process.env.GITHUB_ACTIONS

export default defineConfig({
  test: {
    alias: {
      '@/': new URL('./src/', import.meta.url).pathname,
    },
    reporters: isInCI ? ['default', new GithubActionsReporter()] : ['default', 'html'],
    outputFile: {
      html: './output/reporters/html/index.html',
    },
    coverage: {
      enabled: true,
      reporter: isInCI ? ['json-summary', 'json'] : ['html'],
      provider: 'istanbul', // or 'v8'
      reportsDirectory: './output/coverage',
    },
  },
})

```

Failing tests and report coverage error:

<img width="1141" alt="image" src="https://github.com/davelosert/vitest-coverage-report-action/assets/90383710/398d199a-64db-4732-9c88-f9dc02229002">

Successful tests and report coverage:

<img width="1094" alt="image" src="https://github.com/davelosert/vitest-coverage-report-action/assets/90383710/f5c47e56-405b-40ac-8e67-6216e1f96ef7">

**Comment by goibon** [comment]
You can change your `vite.config.ts` to [use the `reportOnFailure` option.](https://vitest.dev/config/#coverage-reportonfailure), like:
```TS
export default defineConfig({
  test: {
    // ..omitted other fields
    coverage: {
      reportOnFailure: true, // add this one
      // ..omitted other fields
    },
  },
})
```

[The default value of it was changed in Vitest 0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0).

I hope this helps you 🙂

**Comment by JunlinPan-Crypto** [comment]
Thanks @goibon ! The option `reportOnFailure: true` is probably right. 

But I decide to skip coverage report until the tests are passing, since the previous steps prior to test might be falling sometimes and the coverage report obviously doesn't need to be performed (not `always()`). 
In addition, the coverage report mean little for failed tests.

```yaml
- name: 'Report Coverage'
      # if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v2
```
