### ISSUE TITLE
Fail when coverage is not met

### ISSUE THREAD

**Issue by Clonex** [davelosert/vitest-coverage-report-action#314]
Is it possible to make the action fail when the coverage is not met?
I've been working on setting up the coverage report action in our repo, but it still goes green even if I dont meet the coverage goal.

![image](https://github.com/davelosert/vitest-coverage-report-action/assets/408229/803e278b-2667-4b47-9d4e-ee44fae7a482)

Our config looks like this:
```javascript
export default defineConfig({
	test: {
		watch: false,
		threads: false,
		poolOptions: {
			threads: {
				singleThread: true,
			},
		},
		environment: 'jsdom',
		setupFiles: ['dotenv/config'],
		coverage: {
			clean: true,
			cleanOnRerun: true,
			provider: 'v8',
			reporter: ['html', 'json-summary', 'json'],
			reportsDirectory: './coverage',

			lines: 40,
			branches: 40,
			functions: 40,
			statements: 40,
		},
	},
})
```

This is the steps that im doing to use the action.
```yaml
- name: 'Coverage test - Generate'
  run: yarn vitest run --coverage

- name: 'Coverage test - Check'
  if: always()
  uses: davelosert/vitest-coverage-report-action@v2
```

It does however still go green
![image](https://github.com/davelosert/vitest-coverage-report-action/assets/408229/1b5beace-6fa2-4e9f-88d4-cc95d966c61d)
