### ISSUE TITLE
Feature Request: comment coverage for a commit

### ISSUE THREAD

**Issue by rwv** [davelosert/vitest-coverage-report-action#392]
https://github.com/marketplace/actions/commit-comment

**Comment by davelosert** [comment]
I like the idea and will think about it.
Potentially this could be an option over the "normal" Pull-Request Comment.

I might also add the Commit-Short-SHA to the existing Pull-Request as a better identifier as to which commit the comment was last created.

**Comment by davelosert** [comment]
@rwv : I've just implemented this, but it's not released yet. 
I want to put in one more feature before my next release (most likely within the next 2 days).

If you want to "pre-test" this, you can us the action with `@main` for now:

```yml
- uses:  davelosert/vitest-coverage-report-action@main
  with:
    comment-on: "pr,commit"
```
