### ISSUE TITLE
Configurable workspace path

### ISSUE THREAD

**Issue by mattcorner** [davelosert/vitest-coverage-report-action#428]
Currently the workspace path used when parsing the coverage files is `process.cwd()` https://github.com/davelosert/vitest-coverage-report-action/blob/3edd4ea4b65b2b7a43dbfff406ccab91c5dccfd0/src/report/generateFileCoverageHtml.ts#L20

This makes the assumption that the coverage report was generated in the same workspace as the coverage-report-action is running in.

We have a case where vitest runs inside a docker container, but the coverage-report-action runs in the github runner so these paths don't match up. This leads to malformed file coverage links:

![image](https://github.com/user-attachments/assets/7a174c45-8739-45dd-8d30-75b46f8311ff)

I'd propose that the workspacePath is an option that can be defined on the action. Thoughts?

**Comment by davelosert** [comment]
Hey @mattcorner ,
I am sorry, I somehow entirely missed this issue.

You have a fair point here - and this actually might trigger other behavior like described in #438 (which I see in your screenshot as well).

What would the workspace-configuration look like in your example?

**Comment by mattcorner** [comment]
No problem at all. For now I have a workaround where I rewrite the coverage reports with the correct path before proceeding to use this action e.g.

```yaml
- name: Modify coverage report
  run: |
   # Replace /usr/src/react-ui/ with the current working directory in all coverage reports files
   sudo chmod -R 777 test-artifacts/coverage
   for file in test-artifacts/coverage/coverage-summary.json test-artifacts/coverage/coverage-final.json; do
     sed -i "s#/usr/src/react-ui#$(pwd)#g" "$file"
   done
```

Workspace config for me would look something like:
```yaml
- name: "Report coverage"
  uses: davelosert/vitest-coverage-report-action@v2
  if: always()
  with:
    file-coverage-mode: all
    json-summary-path: test-artifacts/coverage/coverage-summary.json
    json-final-path: test-artifacts/coverage/coverage-final.json
    workspacePath: usr/src/react-ui/
```
