### ISSUE TITLE
How do I set up json-summary-compare-path in a monorepo?

### ISSUE THREAD

**Issue by khoilen** [davelosert/vitest-coverage-report-action#480]
My current workflow doesn't show the coverage comparison 

```
 name: Report Coverage
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  name: ${{ matrix.name }}
                  json-summary-path: ./apps/${{ matrix.app }}/coverage/coverage-summary.json
                  json-final-path: ./apps/${{ matrix.app }}/coverage/coverage-final.json
                  json-summary-compare-path: ./apps/${{ matrix.app }}/coverage/coverage-summary.json
```
